//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string cuilt { get; set; }
        public Nullable<int> dni { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string legajo { get; set; }
        public string email { get; set; }
    }
}
